# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crud',
            old_name='addr',
            new_name='address',
        ),
    ]
