# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170808_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='department',
            field=models.CharField(default=django.utils.datetime_safe.date.today, max_length=30),
            preserve_default=False,
        ),
    ]
