# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_crud_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
